
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author egeba
 */
class Musteri{
    private String kullaniciAdi;
    private String parola;
    private String sehir;
    private String tel_no;
    private int bakiye;

    public Musteri(String kullaniciAdi, String parola, String sehir, String tel_no, int bakiye)
    {
        this.kullaniciAdi = kullaniciAdi;
        this.parola = parola;
        this.sehir = sehir;
        this.tel_no = tel_no;
        this.bakiye = bakiye;
    }

    public String getKullaniciAdi()
    {
        return kullaniciAdi;
    }

    public void setKullaniciAdi(String kullaniciAdi)
    {
        this.kullaniciAdi = kullaniciAdi;
    }

    public String getParola()
    {
        return parola;
    }

    public void setParola(String parola)
    {
        this.parola = parola;
    }

    public String getSehir()
    {
        return sehir;
    }

    public void setSehir(String sehir)
    {
        this.sehir = sehir;
    }

    public String getTel_no()
    {
        return tel_no;
    }

    public void setTel_no(String tel_no)
    {
        this.tel_no = tel_no;
    }

    public int getBakiye()
    {
        return bakiye;
    }

    public void setBakiye(int bakiye)
    {
        this.bakiye = bakiye;
    }
    
    
    
    
    
}
public class AnaSayfa extends javax.swing.JFrame
{
    private static  int  gunlukCekilecekMiktar = 1500;

    public static int getGunlukCekilecekMiktar()
    {
        return gunlukCekilecekMiktar;
    }

    public static void setGunlukCekilecekMiktar(int gunlukCekilecekMiktar)
    {
        AnaSayfa.gunlukCekilecekMiktar = gunlukCekilecekMiktar;
    }
private static Musteri inmusteri ;

    public static Musteri getInmusteri()
    {
        return inmusteri;
    }

    public static void setInmusteri(Musteri inmusteri)
    {
        AnaSayfa.inmusteri = inmusteri;
    }

    private static int say=2;
    private static ArrayList<Musteri> musteriler = new ArrayList<Musteri>();
     
    public ArrayList<Musteri> getMusteriler()
    {
        return musteriler;
    }

    public void setMusteriler(ArrayList<Musteri> musteriler)
    {
        this.musteriler = musteriler;
    }
    
    
    /**
     * Creates new form AnaSayfa
     */
    public AnaSayfa()
    {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        AnaEkranPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfmain_kullaniciAdi = new javax.swing.JTextField();
        tfmain_parola = new javax.swing.JPasswordField();
        girisYapButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        goto_registerPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        kayıtOlButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AnaEkranPanel.setBackground(new java.awt.Color(0, 255, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Kullanıcı Adı :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Parola:");

        tfmain_kullaniciAdi.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                tfmain_kullaniciAdiActionPerformed(evt);
            }
        });

        girisYapButton.setText("Giriş Yap");
        girisYapButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                girisYapButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Şifrenizi mi unuttunuz ?");

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 255));
        jLabel7.setText("                      # BARIŞAN BANK #  ");

        javax.swing.GroupLayout AnaEkranPanelLayout = new javax.swing.GroupLayout(AnaEkranPanel);
        AnaEkranPanel.setLayout(AnaEkranPanelLayout);
        AnaEkranPanelLayout.setHorizontalGroup(
            AnaEkranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AnaEkranPanelLayout.createSequentialGroup()
                .addGroup(AnaEkranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AnaEkranPanelLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(AnaEkranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AnaEkranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AnaEkranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfmain_kullaniciAdi)
                                .addComponent(tfmain_parola, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                            .addComponent(girisYapButton, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AnaEkranPanelLayout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AnaEkranPanelLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AnaEkranPanelLayout.setVerticalGroup(
            AnaEkranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AnaEkranPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(AnaEkranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfmain_kullaniciAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AnaEkranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfmain_parola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(girisYapButton)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        goto_registerPanel.setBackground(new java.awt.Color(0, 51, 102));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Hala İnternet Bankacılığına sahip değil misiniz ?");

        jLabel5.setForeground(new java.awt.Color(255, 255, 51));
        jLabel5.setText("Hemen Ara ");

        jLabel6.setForeground(new java.awt.Color(204, 204, 255));
        jLabel6.setText("0546 813 52 22");

        kayıtOlButton.setText("Kayıt Ol");
        kayıtOlButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                kayıtOlButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout goto_registerPanelLayout = new javax.swing.GroupLayout(goto_registerPanel);
        goto_registerPanel.setLayout(goto_registerPanelLayout);
        goto_registerPanelLayout.setHorizontalGroup(
            goto_registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(goto_registerPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(goto_registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(goto_registerPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6))
                    .addGroup(goto_registerPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(84, 84, 84)
                        .addComponent(kayıtOlButton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        goto_registerPanelLayout.setVerticalGroup(
            goto_registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, goto_registerPanelLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(goto_registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(kayıtOlButton))
                .addGap(18, 18, 18)
                .addGroup(goto_registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AnaEkranPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(goto_registerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(AnaEkranPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(goto_registerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfmain_kullaniciAdiActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tfmain_kullaniciAdiActionPerformed
    {//GEN-HEADEREND:event_tfmain_kullaniciAdiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfmain_kullaniciAdiActionPerformed

    private void kayıtOlButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_kayıtOlButtonActionPerformed
    {//GEN-HEADEREND:event_kayıtOlButtonActionPerformed
        
        
        setVisible(false);
        Register registerSayfasi = new Register();
        JOptionPane.showMessageDialog(this, "Sayfadan ayrılmak istediğinize emin misiniz ?");
        registerSayfasi.setVisible(true);
        
    }//GEN-LAST:event_kayıtOlButtonActionPerformed

    private void girisYapButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_girisYapButtonActionPerformed
    {//GEN-HEADEREND:event_girisYapButtonActionPerformed
       String k_adi=tfmain_kullaniciAdi.getText();
       String parola = tfmain_parola.getText();
       if(k_adi.trim().equals("") || parola.trim().equals("")){
           JOptionPane.showMessageDialog(this,"Kullanıcı Adı veya Parola alanı boş bırakılamaz !");
       }
       else{
           for(Musteri musteri : musteriler){
               if(k_adi.equals(musteri.getKullaniciAdi()) && parola.equals(musteri.getParola())){
                   Customer customerScreen = new Customer();
                   JOptionPane.showMessageDialog(this, "Giriş Başarılı!\nBankanız'a Hoşgeldiniz, " +k_adi +"\nBarışan Bank iyi günler diler...");
                   inmusteri = musteri;
                   setVisible(false);
                   
                   customerScreen.setVisible(true);
                   return;
                   
               }
           }
           if(say <= 0){
               JOptionPane.showMessageDialog(this, "Sistem kendini bloke etti !\n !Sorun! : Giriş Hakkı Doldu!...");
               System.exit(0);
           }
           
           JOptionPane.showMessageDialog(this, "Giriş Hatalı !\nKayıtlı değil iseniz Lütfen Kayıt olunuz ..."+say--+" tane giriş hakkınız kaldı.");
           
       }
        
    }//GEN-LAST:event_girisYapButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(AnaSayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(AnaSayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(AnaSayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(AnaSayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                musteriler.add(new Musteri("Ege", "123","Adana","05468135222", 6000));
                musteriler.add(new Musteri("Mustafa", "321","Gülnar","05468135222", 8000));
                musteriler.add(new Musteri("Büşra Ertekin", "789", "Ankara", "05426589587", 100000));
                new AnaSayfa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AnaEkranPanel;
    private javax.swing.JButton girisYapButton;
    private javax.swing.JPanel goto_registerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton kayıtOlButton;
    private javax.swing.JTextField tfmain_kullaniciAdi;
    private javax.swing.JPasswordField tfmain_parola;
    // End of variables declaration//GEN-END:variables
}
