
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author egeba
 */
public class Customer extends javax.swing.JFrame
{

    public int gunlukCekilen = 0;
    public static AnaSayfa anasayfa = new AnaSayfa();

    /**
     * Creates new form Customer
     */
    public Customer()
    {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        bakiyeButton = new javax.swing.JButton();
        paraCekButton = new javax.swing.JButton();
        paraYatirButton = new javax.swing.JButton();
        iletisimButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        goto_anaSayfa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setForeground(new java.awt.Color(102, 102, 255));

        bakiyeButton.setText("Bakiyeniz");
        bakiyeButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                bakiyeButtonActionPerformed(evt);
            }
        });

        paraCekButton.setText("Para Çek");
        paraCekButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                paraCekButtonActionPerformed(evt);
            }
        });

        paraYatirButton.setText("Para Yatır");
        paraYatirButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                paraYatirButtonActionPerformed(evt);
            }
        });

        iletisimButton.setText("İletişim Bilgileriniz");
        iletisimButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                iletisimButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("MÜŞTERİ İŞLEMLERİ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bakiyeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(paraCekButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(paraYatirButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(iletisimButton, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(bakiyeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(paraCekButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(paraYatirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(iletisimButton)
                .addContainerGap())
        );

        goto_anaSayfa.setText("Çıkış");
        goto_anaSayfa.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                goto_anaSayfaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(goto_anaSayfa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(goto_anaSayfa)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bakiyeButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_bakiyeButtonActionPerformed
    {//GEN-HEADEREND:event_bakiyeButtonActionPerformed
        JOptionPane.showMessageDialog(this, "Bakiyeniz : " + anasayfa.getInmusteri().getBakiye());
    }//GEN-LAST:event_bakiyeButtonActionPerformed

    private void paraCekButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_paraCekButtonActionPerformed
    {//GEN-HEADEREND:event_paraCekButtonActionPerformed

        int miktar = Integer.valueOf(JOptionPane.showInputDialog("Çekilecek Miktar : "));
        gunlukCekilen += miktar;

        if (anasayfa.getInmusteri().getBakiye() - miktar < 0)
        {
            JOptionPane.showMessageDialog(this, "Yeterli bakiye bulunmamaktadır !\nÜzgünüz işleminiz gerçekleşmedi...");
            gunlukCekilen -= miktar;
        }
        else if (gunlukCekilen > 1500)
        {
            gunlukCekilen -= miktar;

            JOptionPane.showMessageDialog(this, "Günlük para çekme limitinizi doldurdunuz En yakın şubemize bekleriz...\n!Bilgilendirme! : Limit 1500 Tl dir...");

        }
        else
        {

            anasayfa.getInmusteri().setBakiye(anasayfa.getInmusteri().getBakiye() - miktar);
            JOptionPane.showMessageDialog(this, "Hesabınızdan " + miktar + " TL Çekildi...");

        }
    }//GEN-LAST:event_paraCekButtonActionPerformed

    private void paraYatirButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_paraYatirButtonActionPerformed
    {//GEN-HEADEREND:event_paraYatirButtonActionPerformed
        int miktar2 = Integer.valueOf(JOptionPane.showInputDialog("Yatırılacak Miktar : "));

        // JOptionPane.showMessageDialog(this, "afasdas" , "Ege" , 2);
        anasayfa.getInmusteri().setBakiye(anasayfa.getInmusteri().getBakiye() + miktar2);
        JOptionPane.showMessageDialog(this, "Hesabınız'a " + miktar2 + " TL yatırıldı...\nParanız bizimle güvendedir...\nBarışan Bank");
    }//GEN-LAST:event_paraYatirButtonActionPerformed

    private void goto_anaSayfaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_goto_anaSayfaActionPerformed
    {//GEN-HEADEREND:event_goto_anaSayfaActionPerformed
        JOptionPane.showMessageDialog(this, "Tekrar bekleriz...");
        System.exit(0);
    }//GEN-LAST:event_goto_anaSayfaActionPerformed

    private void iletisimButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_iletisimButtonActionPerformed
    {//GEN-HEADEREND:event_iletisimButtonActionPerformed

        setVisible(false);
        IletisimBilgiler iletisimEkrani = new IletisimBilgiler();
        iletisimEkrani.setVisible(true);
    }//GEN-LAST:event_iletisimButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {

            public void run()
            {
                new Customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bakiyeButton;
    private javax.swing.JButton goto_anaSayfa;
    private javax.swing.JButton iletisimButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton paraCekButton;
    private javax.swing.JButton paraYatirButton;
    // End of variables declaration//GEN-END:variables
}
