
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author egeba
 */
public class IletisimBilgiler extends javax.swing.JFrame
{

    /**
     * Creates new form IletisimBilgiler
     */
    public IletisimBilgiler()
    {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        tfiletisim_telNo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbiletisim_sehir = new javax.swing.JComboBox();
        guncelle_butonu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        bilgiTablosu = new javax.swing.JTable();
        aktarButton = new javax.swing.JButton();
        goto_islemler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("Telefon Numaranız : ");

        tfiletisim_telNo.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                tfiletisim_telNoActionPerformed(evt);
            }
        });

        jLabel2.setText("Yaşadığınız Şehir:");

        cbiletisim_sehir.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Adana", "Adıyaman", "Afyonkarahisar", "Ağrı", "Aksaray", "Amasya", "Ankara", "Antalya", "Ardahan", "Artvin", "Aydın", "Balıkesir", "Bartın", "Batman", "Bayburt", "Bilecik", "Bingöl", "Bitlis", "Bolu", "Burdur", "Bursa", "Çanakkale", "Çankırı", "Çorum", "Denizli", "Diyarbakır", "Düzce", "Edirne", "Elazığ", "Erzincan", "Erzurum", "Eskişehir", "Gaziantep", "Giresun", "Gümüşhane", "Hakkâri", "Hatay", "Iğdır", "Isparta", "İstanbul", "İzmir", "Kahramanmaraş", "Karabük", "Karaman", "Kars", "Kastamonu", "Kayseri", "Kilis", "Kırıkkale", "Kırklareli", "Kırşehir", "Kocaeli", "Konya", "Kütahya", "Malatya", "Manisa", "Mardin", "Mersin", "Muğla", "Muş", "Nevşehir", "Niğde", "Ordu", "Osmaniye", "Rize", "Sakarya", "Samsun", "Şanlıurfa", "Siirt", "Sinop", "Sivas", "Şırnak", "Tekirdağ", "Tokat", "Trabzon", "Tunceli", "Uşak", "Van", "Yalova", "Yozgat", "Zonguldak" }));
        cbiletisim_sehir.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cbiletisim_sehirActionPerformed(evt);
            }
        });

        guncelle_butonu.setText("Bilgileri Güncelle");
        guncelle_butonu.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                guncelle_butonuActionPerformed(evt);
            }
        });

        bilgiTablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Şehir", "İsim", "Telefon"
            }
        ));
        jScrollPane1.setViewportView(bilgiTablosu);

        aktarButton.setText("Bilgilerini Aktar");
        aktarButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                aktarButtonActionPerformed(evt);
            }
        });

        goto_islemler.setText("Müşteri İşlemleri'ne Dön");
        goto_islemler.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                goto_islemlerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(39, 39, 39)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(32, 32, 32)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfiletisim_telNo)
                                .addComponent(cbiletisim_sehir, 0, 126, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(aktarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(guncelle_butonu)))
                    .addComponent(goto_islemler))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfiletisim_telNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbiletisim_sehir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guncelle_butonu)
                    .addComponent(aktarButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 291, Short.MAX_VALUE)
                .addComponent(goto_islemler)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfiletisim_telNoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tfiletisim_telNoActionPerformed
    {//GEN-HEADEREND:event_tfiletisim_telNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfiletisim_telNoActionPerformed

    private void cbiletisim_sehirActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cbiletisim_sehirActionPerformed
    {//GEN-HEADEREND:event_cbiletisim_sehirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbiletisim_sehirActionPerformed

    private void aktarButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_aktarButtonActionPerformed
    {//GEN-HEADEREND:event_aktarButtonActionPerformed
        DefaultTableModel model;
        model = (DefaultTableModel) bilgiTablosu.getModel();
        Object[] eklenecek =
        {
            Customer.anasayfa.getInmusteri().getSehir(),  Customer.anasayfa.getInmusteri().getKullaniciAdi(),  Customer.anasayfa.getInmusteri().getTel_no()
        };

        model.addRow(eklenecek);
        JOptionPane.showMessageDialog(this, "Bilgileriniz başarıyla aktarıldı...");
    }//GEN-LAST:event_aktarButtonActionPerformed

    private void goto_islemlerActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_goto_islemlerActionPerformed
    {//GEN-HEADEREND:event_goto_islemlerActionPerformed

        Customer islemlerEkrani = new Customer();
        setVisible(false);
        islemlerEkrani.setVisible(true);
    }//GEN-LAST:event_goto_islemlerActionPerformed

    private void guncelle_butonuActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_guncelle_butonuActionPerformed
    {//GEN-HEADEREND:event_guncelle_butonuActionPerformed
        DefaultTableModel model;
        model = (DefaultTableModel) bilgiTablosu.getModel();

        String yeni_tel = tfiletisim_telNo.getText();
        String yeniSehir = cbiletisim_sehir.getSelectedItem().toString();

        
        Customer.anasayfa.getInmusteri().setTel_no(yeni_tel);
        Customer.anasayfa.getInmusteri().setSehir(yeniSehir);
        model.setValueAt( Customer.anasayfa.getInmusteri().getSehir(), 0, 0);
        model.setValueAt( Customer.anasayfa.getInmusteri().getTel_no(), 0, 2);

    }//GEN-LAST:event_guncelle_butonuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(IletisimBilgiler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(IletisimBilgiler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(IletisimBilgiler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(IletisimBilgiler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new IletisimBilgiler().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aktarButton;
    private javax.swing.JTable bilgiTablosu;
    private javax.swing.JComboBox cbiletisim_sehir;
    private javax.swing.JButton goto_islemler;
    private javax.swing.JButton guncelle_butonu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tfiletisim_telNo;
    // End of variables declaration//GEN-END:variables
}
